/*
 * Copyright 2020 United States Government
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifndef __MTAB_MEASUREMENT_TYPE_H__
#define __MTAB_MEASUREMENT_TYPE_H__

#include <stdio.h>
#include <mntent.h>

#define MTAB_MEASUREMENT_TYPE_NAME "mtab"
#define MTAB_MEASUREMENT_TYPE_MAGIC (0xABCDABCD)

/*! \file
 * measurement_type for mtab (mount table) data. Defines the
 * mtab_measurement_data type that holds a GList of mntent structures.
 * Instances of this data type are generated by the mtabasp
 */

typedef struct mtab_data {
    measurement_data d;
    GList *mntents;
} mtab_data;

/**
 * Add a copy of the mntent structure @ent to the
 * mtab_measurement_data @d's internal list of entries.
 *
 * Handles the allocation and copying of the @ent so that the return
 * of @getmntent can be passed directly to this function.
 */
int mtab_data_add_mntent(mtab_data *d, struct mntent *ent);

extern measurement_type mtab_measurement_type;

#endif
